## Introduction to Numerical Computing with NumPy

### from page no 12 in slides

In [104]:
a=[1,2,3,4,5,6]

In [12]:
b=[7,8,9,10,11,10]

In [13]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 10]

In [14]:
result=[]
for first ,sec in zip(a, b):
    result.append(first + sec)
    

In [15]:
result

[8, 10, 12, 14, 16, 16]

In [16]:
import numpy as np

In [20]:
a=np.array([0,1,2,3,4,5,6])

In [21]:
type(a)

numpy.ndarray

In [22]:
a.dtype

dtype('int32')

In [46]:
f= np.array([1,2.2,2.3,4,5,6,7])

In [47]:
type(f)

numpy.ndarray

In [48]:
f.dtype

dtype('float64')

In [49]:
f

array([1. , 2.2, 2.3, 4. , 5. , 6. , 7. ])

In [50]:
f[0]

1.0

In [51]:
f[3]

4.0

In [52]:
f[0]=10

In [53]:
f

array([10. ,  2.2,  2.3,  4. ,  5. ,  6. ,  7. ])

In [54]:
f[0]=11.5

In [55]:
f

array([11.5,  2.2,  2.3,  4. ,  5. ,  6. ,  7. ])

In [56]:
a

array([11,  1,  2,  3,  4,  5,  6])

In [57]:
a[0]=11.5

In [58]:
a

array([11,  1,  2,  3,  4,  5,  6])

In [59]:
a.ndim #ndim dimension of the array 

1

In [60]:
a.shape 

(7,)

In [61]:
f.shape # shape is always a tuple 

(7,)

In [62]:
a.size

7

In [64]:
a

array([11,  1,  2,  3,  4,  5,  6])

In [65]:
f

array([11.5,  2.2,  2.3,  4. ,  5. ,  6. ,  7. ])

In [63]:
a + f #due to vectorizd operation 

array([22.5,  3.2,  4.3,  7. ,  9. , 11. , 13. ])

In [66]:
a*10

array([110,  10,  20,  30,  40,  50,  60])

In [67]:
#universil funtion (ufuncs)

In [68]:
np.sin(a)

array([-0.99999021,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ])

In [69]:
np.cos(a)

array([ 0.0044257 ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029])

In [70]:
#2 dimension array same concept for 2d 3d 5d ...

In [93]:
b=np.array([[0,1,2,3],[5,6,7,8]])

In [94]:
b

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [95]:
b.dtype

dtype('int32')

In [96]:
b.shape #shape =( row ,columns)

(2, 4)

In [97]:
b.ndim

2

In [98]:
b[1]

array([5, 6, 7, 8])

In [99]:
b[1,3]

8

In [100]:
b[1,3]=10

In [101]:
b[1,3]

10

In [102]:
b

array([[ 0,  1,  2,  3],
       [ 5,  6,  7, 10]])

### slicing

In [106]:
h=np.array([11,12,34,44,5])

In [109]:
h[1:3]

array([12, 34])

In [110]:
h[-4:3]

array([12, 34])

In [111]:
h[1:-2]

array([12, 34])

In [112]:
h[:3]

array([11, 12, 34])

In [113]:
h[1:]

array([12, 34, 44,  5])

In [114]:
h[::2]

array([11, 34,  5])

In [116]:
h[2:4]

array([34, 44])

In [117]:
c=np.array([[0,1,2,3],[5,6,7,8]])

In [118]:
c

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [119]:
c[0,2:4]

array([2, 3])

In [120]:
c[:,2]

array([2, 7])

In [122]:
d=np.arange(25).reshape(5,5)

In [123]:
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [124]:
d[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [125]:
d[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [126]:
d[4,:]

array([20, 21, 22, 23, 24])

In [127]:
d[4]

array([20, 21, 22, 23, 24])

In [130]:
d[4,0::2]

array([20, 22, 24])

In [131]:
d.shape

(5, 5)

In [137]:
d[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [140]:
d[1::2,:-1:2]

array([[ 5,  7],
       [15, 17]])

In [143]:
g=np.array([1,2,3,4,5])

In [144]:
j=g[2:4]

In [145]:
j

array([3, 4])

In [146]:
g

array([1, 2, 3, 4, 5])

In [147]:
j[0]

3

In [148]:
j[0]= -5

In [149]:
j

array([-5,  4])

In [150]:
g

array([ 1,  2, -5,  4,  5])

In [151]:
j=g.copy()

In [152]:
j

array([ 1,  2, -5,  4,  5])

In [153]:
g

array([ 1,  2, -5,  4,  5])

In [154]:
g[-2:]

array([4, 5])

In [155]:
g[-2:]=[-4,-3]

In [156]:
g

array([ 1,  2, -5, -4, -3])

In [157]:
g[-2:]=99

In [158]:
g

array([ 1,  2, -5, 99, 99])

In [187]:
[0]

[0]

### fancy indexing

In [165]:
np.array.__call__([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [170]:
z=np.array([-2,3,-4,6,9])

In [172]:
z<0

array([ True, False,  True, False, False])

In [179]:
Masks=z<0

In [180]:
negative = z < 0 

In [184]:
z[negative] 

array([-2, -4])

In [185]:
z[negative] =0

In [186]:
z

array([0, 3, 0, 6, 9])

In [188]:
# selct element by the number itself

In [189]:
d=np.arange(25).reshape(5,5)

In [190]:
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [191]:
# we want to select element 2

In [192]:
d[[0],[2]]

array([2])

In [194]:
# we want to select element 13 with 2
d[[0, 2],[2,3]]


array([ 2, 13])

In [198]:
# we want to select element  16 and 19 with 13,2 
d[[0, 2 ,3,3],[2,3,1,-1]]

array([ 2, 13, 16, 19])

In [200]:
# alternative we want to select element  16 and 19 with 13,2 
d[[0, 2 ,3,3],[2,3,1,4]]

array([ 2, 13, 16, 19])

In [201]:
d%3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]], dtype=int32)

In [203]:
1%3 

1

In [204]:
0%3

0

In [205]:
4%3 #mean one number is left 

1

In [207]:
3%3 # there is no element left  

0

In [210]:
#if we divid 8 by 3 then 2 number is left  8= 6+2 ---> 6/3 +2 --> 0 +2  (6/3 = 0 bcoz there is no element which is left )
8 % 3

2

In [211]:
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [212]:
d % 3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]], dtype=int32)

In [213]:
d[d%3]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [214]:
d % 3 ==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [216]:
d[d % 3 ==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [218]:
np.nan

nan

In [219]:
np.nan+1

nan

In [224]:
a=np.ones((5,6))

In [225]:
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [228]:
a.sum(axis=1)

array([6., 6., 6., 6., 6.])

In [229]:
a.shape

(5, 6)

In [231]:
a.sum(axis=1).shape

(5,)

In [233]:
a.sum(axis=0).shape

(6,)

### array calculation method 

In [234]:
a=np.array([[1,2,3,4,5,6],[5,6,7,8,9,0]])

In [235]:
a

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9, 0]])

In [236]:
np.sum(a)

56

In [237]:
a.sum(axis=0)

array([ 6,  8, 10, 12, 14,  6])

In [241]:
np.sum(a , axis=0)

array([ 6,  8, 10, 12, 14,  6])

In [243]:
np.min(a)

0

In [248]:
np.max(a , axis=1)

array([6, 9])

In [246]:
np.ptp(a)

9

In [249]:
a.argmax() #interested in the location of a min/max, not the value  

10

In [251]:
a.argmin()

11

In [252]:
 np.unravel_index(a.argmax(), a.shape) #give the location of the max value as will as coordite 

(1, 4)

In [255]:
a=np.array([-1,2,-3,0])

In [260]:
a=np.array([-1,2,5,5])

In [261]:
a== a.max()

array([False, False,  True,  True])

In [262]:
np.where(a== a.max())

(array([2, 3], dtype=int64),)

In [267]:
np.where(a >0)

(array([1, 2, 3], dtype=int64),)

In [268]:
a= np.arange(6)

In [269]:
a

array([0, 1, 2, 3, 4, 5])

In [270]:
a=np.array([[1,2,3,4],[3,5,6,7]])

In [271]:
a

array([[1, 2, 3, 4],
       [3, 5, 6, 7]])

In [278]:
a.T.shape # traspose swape the order of axes 

(4, 2)

In [279]:
a.T

array([[1, 3],
       [2, 5],
       [3, 6],
       [4, 7]])

In [280]:
a.T.T.shape

(2, 4)

In [282]:
a.T.strides

(4, 16)

In [283]:
a.reshape

<function ndarray.reshape>